apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-05-29T14:29:57Z

  labels:
    app: mac-graph-0
  name: mac-graph-0
  namespace: default

spec:
  replicas: 20
  selector:
    matchLabels:
      app: mac-graph-0
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mac-graph-0
    spec:
      containers:
      - command:
        - ./run-k8.sh
        env:
        - name: N_WORKERS
          value: "5"
        - name: RUN
          value: default
        - name: AMQP_URL
          value: amqp://admin:secretpassword@one-rabbitmq.default.svc.cluster.local:5672
        - name: input-dir
          value: gs://octavian-static/download/mac-graph/sa-sp
        image: gcr.io/octavian-181621/github-octavian-ai-mac-graph
        imagePullPolicy: Always
        name: github-octavian-ai-mac-graph
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --election=mac-graph-0-leader
        - --http=localhost:4040
        image: gcr.io/google_containers/leader-elector:0.4
        imagePullPolicy: IfNotPresent
        name: leader-elector
        ports:
        - containerPort: 4040
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 42
  conditions:
  - lastTransitionTime: 2018-05-29T14:29:57Z
    lastUpdateTime: 2018-05-29T14:29:57Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 11
  readyReplicas: 42
  replicas: 42
  updatedReplicas: 42
